config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :events
  resources :name_cards

end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/name_card.rb
class NameCard < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:session_no, :event_name, :date, :coach_name)
    end
end

app/controllers/name_cards_controller.rb
class NameCardsController < ApplicationController
  before_action :set_name_card, only: [:show, :edit, :update, :destroy]

  # GET /name_cards
  # GET /name_cards.json
  def index
    @name_cards = NameCard.all
  end

  # GET /name_cards/1
  # GET /name_cards/1.json
  def show
  end

  # GET /name_cards/new
  def new
    @name_card = NameCard.new
  end

  # GET /name_cards/1/edit
  def edit
  end

  # POST /name_cards
  # POST /name_cards.json
  def create
    @name_card = NameCard.new(name_card_params)

    respond_to do |format|
      if @name_card.save
        format.html { redirect_to @name_card, notice: 'Name card was successfully created.' }
        format.json { render :show, status: :created, location: @name_card }
      else
        format.html { render :new }
        format.json { render json: @name_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /name_cards/1
  # PATCH/PUT /name_cards/1.json
  def update
    respond_to do |format|
      if @name_card.update(name_card_params)
        format.html { redirect_to @name_card, notice: 'Name card was successfully updated.' }
        format.json { render :show, status: :ok, location: @name_card }
      else
        format.html { render :edit }
        format.json { render json: @name_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /name_cards/1
  # DELETE /name_cards/1.json
  def destroy
    @name_card.destroy
    respond_to do |format|
      format.html { redirect_to name_cards_url, notice: 'Name card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_name_card
      @name_card = NameCard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def name_card_params
      params.require(:name_card).permit(:given_name, :fax, :cell_phone, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/name_cards_helper.rb
module NameCardsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :session_no %><br>
    <%= f.text_field :session_no %>
  </div>
  <div class="field">
    <%= f.label :event_name %><br>
    <%= f.text_field :event_name %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :coach_name %><br>
    <%= f.text_field :coach_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<body>

<style type="text/css">

#navbar {
width:50%;
height:40px;
background-color:#FFF;
}

#navbar ul {
width:80%;
margin:0 auto 0 auto;
}

#navbar ul li {
float:left;
color:#CC0000;
padding:0 20px 0 20px;
border-right:1px solid #FFF;
border-left:1px solid #FFF;
height:40px;
list-style:none;
display:block;
line-height:40px;
text-align:center;
cursor:pointer;
}

#navbar ul li:hover {
background-color:#CCC;
}

</style>
    <div id="navbar">

        <ul>
            <li><a href="/aboutus.html">About Us</a></li>
            <li>Our Committee</li>
            <li><a href="/events">Events</a></li>
            <li>Sponsors</li>
           
        </ul>
        
            


    </div>

</body>

<p id="notice"><%= notice %></p>

<h1>Our Past Events</h1>

<table>
  <thead>
    <tr>
      <th>Session no</th>
      <th>Event name</th>
      <th>Date</th>
      <th>Coach name</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.session_no %></td>
        <td><%= event.event_name %></td>
        <td><%= event.date %></td>
        <td><%= event.coach_name %></td>
      
       <% 
=begin %>
       
       <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td> 
       
       <% 
=end %>
       
      
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Session no:</strong>
  <%= @event.session_no %>
</p>

<p>
  <strong>Event name:</strong>
  <%= @event.event_name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Coach name:</strong>
  <%= @event.coach_name %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AislinnApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/name_cards/_form.html.erb
<%= form_for(@name_card) do |f| %>
  <% if @name_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@name_card.errors.count, "error") %> prohibited this name_card from being saved:</h2>

      <ul>
      <% @name_card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :given_name %><br>
    <%= f.text_field :given_name %>
  </div>
  <div class="field">
    <%= f.label :fax %><br>
    <%= f.text_field :fax %>
  </div>
  <div class="field">
    <%= f.label :cell_phone %><br>
    <%= f.text_field :cell_phone %>
  </div>
   <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/name_cards/edit.html.erb
<h1>Editing Name Card</h1>

<%= render 'form' %>

<%= link_to 'Show', @name_card %> |
<%= link_to 'Back', name_cards_path %>

app/views/name_cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Name Cards</h1>

<table>
  <thead>
    <tr>
      <th>Given name</th>
      <th>Fax</th>
      <th>Cell phone</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @name_cards.each do |name_card| %>
      <tr>
        <td><%= name_card.given_name %></td>
        <td><%= name_card.fax %></td>
        <td><%= name_card.cell_phone %></td>
        <td><%= name_card.address %></td>
        <td><%= link_to 'Show', name_card %></td>
        <td><%= link_to 'Edit', edit_name_card_path(name_card) %></td>
        <td><%= link_to 'Destroy', name_card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Name card', new_name_card_path %>

app/views/name_cards/new.html.erb
<h1>New Name Card</h1>

<%= render 'form' %>

<%= link_to 'Back', name_cards_path %>

app/views/name_cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Given name:</strong>
  <%= @name_card.given_name %>
</p>

<p>
  <strong>Fax:</strong>
  <%= @name_card.fax %>
</p>

<p>
  <strong>Cell phone:</strong>
  <%= @name_card.cell_phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @name_card.address %>
</p>

<%= link_to 'Edit', edit_name_card_path(@name_card) %> |
<%= link_to 'Back', name_cards_path %>